### ISSUE TITLE
VisibleCmdlets can only be defined as a String

### ISSUE THREAD

**Issue by mrhockeymonkey** [ChrisLGardner/JeaDsc#31]
I'm not sure if this is by design and just an omission in the demo but in [here](https://github.com/ChrisLGardner/JeaDsc/blob/09a2d9a58e7dabf78a58a4a4099b2ad09cee31ef/DSCClassResources/DemoConfig.ps1#L8) you give an example passing in a hash table to define the visible cmdlets. 

when I try this I get an error:
```powershell
ConvertTo-MOFInstance : System.ArgumentException error processing property 'VisibleCmdlets' OF TYPE 'JeaRoleCapabilities': Value of type 'System.Object[]' is not allowed in hashtable. Supported types : [String], [Char], [Int64], 
[UInt64], [Double], [Bool] ,[DateTime] and [ScriptBlock].
```

The only way I can get this to work along side other cmdlets is to pass an array of strings as such:

```powershell
JeaRoleCapabilities RoleCapability 
{
    Path = 'C:\Program Files\WindowsPowerShell\Modules\JeaRc\RoleCapabilities\MyJea.psrc'
    VisibleCmdlets = @(
        'Get-Command',
        'Measure-Object',
        'Where-Object',
        'Select-Object',
        'Enter-PSSession',
        'Out-Default',
        'Exit-PSSession',
        'Out-String',
        'Out-Null',
        'Set-Variable',
        'Invoke-CimMethod',
        'Set-StrictMode',
        'Write-Output',
        'Remove-Item', 
        "@{Name = 'New-Item'; Parameters = @(@{Name = 'ItemType'; ValidateSet = 'Directory'}, @{Name = 'Path'}, @{Name = 'Name'})}"
    )

}
```

Is this expected? The demo indicates it should be possible but perhaps its just out of date.

**Comment by ChrisLGardner** [comment]
Thats the intended way it should work due to the fact that MOF files are
just plain text. I'll update the examples to make use of strings rather
than real hashtables.
