### ISSUE TITLE
ComplexObjectsEqual function may lead to false 'Non compliant' status

### ISSUE THREAD

**Issue by jnury** [ChrisLGardner/JeaDsc#7]
The ComplexObjectsEqual sometimes generate a false positive in detecting differences where there is not.

It occurs mainly when adding new user/group to an existing endpoint.

The problem is that order of keys in a hashtable is not garanteed. And the ComplexObjectsEqual only use ConvertTo-Json to compare 2 hashtables.

There are 2 fix proposals for this issue: 

- https://github.com/PowerShell/JEA/pull/57 (probably the best one)
- https://github.com/PowerShell/JEA/pull/47 (the one I use for many months on hundred of nodes)

**Comment by ChrisLGardner** [comment]
I'll pull the newer one over when I get a chance this week.
________________________________
